routes/web.php
<?php

use App\Http\Livewire\Henni;
use App\Http\Livewire\BookComponent;
use App\Http\Livewire\GenreComponent;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\FavoriteComponent;
use App\Http\Livewire\DashboardComponent;
use App\Http\Livewire\UserComponent;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', DashboardComponent::class)->name('dashboard');
    Route::get('henni', Henni::class)->name('HENNI');
    Route::get('genres', GenreComponent::class)->name('GENRE');
    Route::get('books', BookComponent::class)->name('BOOK');
    Route::get('favorites', FavoriteComponent::class)->name('FAVORITE');
    Route::get('users', UserComponent::class)->name('USER');
});

app/Http/Livewire/BookComponent.php
<?php

namespace App\Http\Livewire;

use App\Models\Book;
use App\Models\Genre;
use Livewire\Component;
use App\Traits\BookService;

class BookComponent extends Component
{
    use BookService;

    public $showCreate = false;
    public $showConfirmation = false;

    public $state = [
        'title' => '',
        'author' => '',
        'link' => '',
        'short_description' => '',
        'cover' => ''
    ];

    public $editId;
    public $bookToDelete;

    public $selectedGenres = [];

    protected $rules = [
        'state.title' => 'required',
        'state.author' => 'required',
        'state.link' => 'required',
        'state.short_description' => 'required',
        'selectedGenres' => 'required'
    ];

    /* protected $queryString = [
        'showCreate' => ['except'=>false]
    ]; */

    public function render()
    {
        return view('livewire.book-component')->with([
            'books' => Book::with([
                'genres',
                'likes',
                'user_like',
                'dislikes',
                'user_dislike',
                'user_favorite',
                'user'
            ])->get(),
            'genres' => Genre::all(),
        ]);
    }

    public function showCreateForm()
    {
        $this->showCreate = !$this->showCreate;
    }

    public function save()
    {
        $this->validate();
        //dd($this->state);
        if ($this->editId) {
            $book = Book::find($this->editId);
            $book->update($this->state);
        } else {
            $book = Book::create(array_merge(['user_id' => auth()->id()], $this->state));
        }

        $book->genres()->sync($this->selectedGenres);

        $this->reset();
    }

    public function cancel()
    {
        $this->reset();
    }

    public function editBook(Book $book)
    {
        $book->load('genres');

        $this->editId = $book->id;
        $this->showCreate = true;

        $this->state['title'] = $book->title;
        $this->state['author'] = $book->author;
        $this->state['short_description'] = $book->short_description;
        $this->state['link'] = $book->link;

        foreach ($book->genres as $genre) {
            $this->selectedGenres[] = $genre->id;
        }
    }

    public function confirmDeleteBook(Book $book)
    {
        $this->bookToDelete = $book;
        $this->showConfirmation = true;
    }

    public function cancelDelete()
    {
        $this->reset();
    }

    public function deleteBook()
    {
        $this->bookToDelete->delete();

        $this->reset();
    }

    public function selectGenre(int $genre_id)
    {
        if (($key = array_search($genre_id, $this->selectedGenres)) !== false) {
            unset($this->selectedGenres[$key]);
        } else {
            $this->selectedGenres[] = $genre_id;
        }
    }
}

app/Http/Livewire/DashboardComponent.php
<?php

namespace App\Http\Livewire;

use App\Models\Book;
use App\Models\User;
use App\Models\Genre;
use App\Traits\BookService;
use Livewire\Component;

class DashboardComponent extends Component
{
    use BookService;

    public function render()
    {
        return view('dashboard')->with([
            'genreCount' => Genre::count(),
            'bookCount' => Book::count(),
            'userCount' => User::count(),
            'recentBooks' => Book::orderBy('created_at', 'desc')->take(1)->with([
                'genres',
                'likes',
                'user_like',
                'dislikes',
                'user_dislike',
                'user_favorite',
                'user'
            ])->get(),
            'popularBooks' => Book::take(1)->with([
                'genres',
                'likes',
                'user_like',
                'dislikes',
                'user_dislike',
                'user_favorite',
                'user'
            ])->withCount('likes')->orderBy('likes_count', 'desc')->get()
        ]);
    }
}

app/Http/Livewire/FavoriteComponent.php
<?php

namespace App\Http\Livewire;

use App\Models\Favorite;
use Livewire\Component;

class FavoriteComponent extends Component
{
    public function render()
    {
        return view('livewire.favorite-component')->with([
            'favorites'=>Favorite::with('book')->where('user_id',auth()->id())->get()
        ]);
    }

    public function markAsRead(Favorite $favorite)
    {
        $favorite->read = !$favorite->read;
        $favorite->save();
    }

    public function deleteFavorite(Favorite $favorite)
    {
        $favorite->delete();
    }
}

app/Http/Livewire/GenreComponent.php
<?php

namespace App\Http\Livewire;

use App\Models\Book;
use App\Models\Genre;
use Livewire\Component;
use App\Traits\BookService;

class GenreComponent extends Component
{

    use BookService;

    public $showCreate = false;

    public $name, $genreId, $selectedGenre;

    public $genre, $editId;

    protected $queryString = [
        'genreId'
    ];

    public function render()
    {
        if ($this->genreId) {
            $this->selectedGenre = Genre::with('books')->find($this->genreId);
        }
        return view('livewire.genre-component')->with([
            'genres' => Genre::withCount('books')->orderBy('name')->get(),
        ]);
    }

    public function showCreateForm()
    {
        $this->showCreate = !$this->showCreate;
    }

    public function save()
    {
        if ($this->editId) {
            $genre = Genre::find($this->editId);
            $genre->name = $this->name;
            $genre->save();
        } else {
            Genre::create([
                'name' => $this->name
            ]);
        }


        $this->reset();
    }

    public function cancel()
    {
        $this->reset();
    }

    public function editGenre(Genre $genre)
    {
        $this->showCreate = true;
        $this->editId = $genre->id;
        $this->name = $genre->name;
    }

    public function deleteGenre(Genre $genre)
    {
        $genre->delete();
    }

    public function editBook(Book $book)
    {
        $book->load('genres');

        $this->editId = $book->id;
        $this->showCreate = true;

        $this->state['title'] = $book->title;
        $this->state['author'] = $book->author;
        $this->state['short_description'] = $book->short_description;
        $this->state['link'] = $book->link;

        foreach ($book->genres as $genre) {
            $this->selectedGenres[] = $genre->id;
        }
    }
}

app/Http/Livewire/Henni.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Henni extends Component
{
    public function render()
    {
        return view('livewire.henni');
    }
}

app/Http/Livewire/UserComponent.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

class UserComponent extends Component
{
    public function render()
    {
        return view('livewire.user-component')->with([
            'users' => User::withCount('books')->get()
        ]);
    }
}

resources/views/livewire/book-component.blade.php
<div>
    <x-slot name="header">
        <h2 class="text-2xl font-semibold leading-tight text-gray-800">
            {{ __('Book list(◠‿◠) ') }}
        </h2>
    </x-slot>
    <div class="p-5 mx-auto mt-10 bg-white rounded-lg shadow-lg max-w-7xl">
        <div class="flex justify-between w-full py-4">
            <h1 class="text-2xl">All books ٩(˘◡˘)۶ </h1>

            <button class="px-2 py-1 text-pink-400 bg-pink-200 rounded hover:bg-pink-400 hover:text-white"
                wire:click="showCreateForm">Neuer Eintrag</button>
        </div>
        @if ($showCreate)
            <div class="w-full py-2">
                <x-jet-label for="title" value="{{ __('Titel') }}" />
                <x-jet-input id="title" class="block w-full mt-1" type="text" name="title" wire:model="state.title"
                    required />
                <x-jet-label class="mt-2" for="author" value="{{ __('Autor') }}" />
                <x-jet-input id="author" class="block w-full mt-1" type="text" name="author" wire:model="state.author"
                    required />
                <x-jet-label class="mt-2" for="link" value="{{ __('Link (Amazon etc.)') }}" />
                <x-jet-input id="link" class="block w-full mt-1" type="text" name="link" wire:model="state.link"
                    required />
                <x-jet-label class="mt-2" for="short_description" value="{{ __('Kurzbeschreibung') }}" />
                <textarea id="short_description" name="short_description" wire:model="state.short_description"
                    class="w-full border border-gray-300"></textarea>
                <x-jet-label class="mt-2" for="genres" value="{{ __('Genres') }}" />
                <div class="flex flex-wrap w-full">
                    @foreach ($genres as $genre)
                        <button type="button" wire:click="selectGenre({{ $genre->id }})"
                            @class([
                                'flex px-2 py-1 mb-2 mr-2 text-xs rounded text-white',
                                'bg-pink-600 hover:bg-pink-800' => in_array($genre->id, $selectedGenres),
                                'bg-blue-600 hover:bg-blue-800' => !in_array($genre->id, $selectedGenres)
                            ])>
                            {{ $genre->name }}
                        </button>
                    @endforeach
                </div>
                <div class="flex justify-between w-full pt-5">
                    <button class="px-2 py-1 text-white bg-red-800 rounded hover:bg-red-400"
                        wire:click="cancel">Abbrechen</button>
                    <button class="px-2 py-1 text-pink-400 bg-pink-200 rounded hover:bg-pink-400 hover:text-white"
                        wire:click="save">Speichern</button>
                </div>
            </div>
        @else
            @foreach ($books as $book)
                <div class="flex w-full">
                    <div class="flex w-full">
                        <div class="flex pr-1">
                            @if (!$book->user_favorite)
                                <x-heroicon-o-bookmark wire:click="favoriteBook({{ $book->id }})"
                                    class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                            @else
                                <x-heroicon-s-bookmark wire:click="favoriteBook({{ $book->id }})"
                                    class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                            @endif
                        </div>
                        <h2 class="text-lg">{{ $book->title }}</h2>
                        <div class="flex">
                            @if (!$book->user_like)
                                <x-heroicon-o-thumb-up wire:click="likeBook({{ $book->id }})"
                                    class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                            @else
                                <x-heroicon-s-thumb-up wire:click="likeBook({{ $book->id }})"
                                    class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                            @endif
                            <span class="mt-2 ml-2 text-xs text-pink-600">({{ $book->likes->count() }})</span>
                        </div>
                        <div class="flex">
                            @if (!$book->user_dislike)
                                <x-heroicon-o-thumb-down wire:click="dislikeBook({{ $book->id }})"
                                    class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                            @else
                                <x-heroicon-s-thumb-down wire:click="dislikeBook({{ $book->id }})"
                                    class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                            @endif
                            <span class="mt-2 ml-2 text-xs text-pink-600">({{ $book->dislikes->count() }})</span>
                        </div>
                        <div class="flex pl-2 space-x-2">
                            @if ($book->user_id === auth()->id())
                                <x-heroicon-o-pencil wire:click.prevent="editBook({{ $book->id }})"
                                    class="w-5 h-5 ml-5 text-pink-500 cursor-pointer" />
                                <x-heroicon-o-trash wire:click.prevent="confirmDeleteBook({{ $book->id }})"
                                    class="w-5 h-5 ml-5 text-pink-500 cursor-pointer" />
                            @endif
                        </div>
                    </div>
                </div>
                <div class="w-full px-12 pb-2">
                    by {{ $book->author }} <span class="text-xs">({{ $book->user->name }})</span>
                    <hr class="my-2">
                    <p>
                        {{ $book->short_description }}
                    </p>
                    <p class="py-2">
                        <a class="px-2 py-1 text-xs text-white bg-blue-700 rounded hover:bg-blue-500" target="_blank"
                            class="hover:underline" href="{{ $book->link }}">Buy Online</a>
                    </p>
                </div>
                <div class="flex w-full px-12 pb-10 space-x-2">
                    @foreach ($book->genres as $genre)
                        <a href="{{ route('GENRE', ['genreId' => $genre->id]) }}"
                            class="px-2 py-1 text-xs text-white bg-pink-600 rounded-lg hover:bg-pink-300 hover:text-pink-600">{{ $genre->name }}</a>
                    @endforeach
                </div>
            @endforeach
        @endif
    </div>
    <x-jet-dialog-modal wire:model='showConfirmation'>
        <x-slot name="title">Delete Book?</x-slot>
        <x-slot name="content">
            The book {{ $bookToDelete->title ?? '' }} will be deleted.
        </x-slot>
        <x-slot name="footer">
            <div class="flex space-x-4">
                <x-jet-button type="button" wire:click="cancelDelete">Abbrechen</x-jet-button>
                <x-jet-danger-button type="button" wire:click="deleteBook">Löschen</x-jet-danger-button>
            </div>
        </x-slot>
    </x-jet-dialog-modal>
</div>

resources/views/livewire/favorite-component.blade.php
<div>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Meine Favoriten') }}
        </h2>
    </x-slot>
    <div class="p-5 mx-auto mt-10 bg-white rounded-lg shadow-lg max-w-7xl">

        <div class="flex flex-col w-full space-y-2">
            @foreach ($favorites as $favorite)
            <div class="flex space-x-2">
                @if($favorite->read)
                <x-heroicon-o-x wire:click="markAsRead({{$favorite->id}})" class="w-4 h-4 text-red-600 cursor-pointer"></x-heroicon-o-pencil>
                @else
                <x-heroicon-o-check wire:click="markAsRead({{$favorite->id}})" class="w-4 h-4 text-red-600 cursor-pointer"></x-heroicon-o-pencil>
                @endif

                <x-heroicon-o-trash wire:click="deleteFavorite({{$favorite->id}})" class="w-4 h-4 text-pink-600 cursor-pointer"></x-heroicon-o-pencil>
                <a @class([
                    'line-through' => $favorite->read
                ]) href="{{route('BOOK',['bookId'=>$favorite->book->id])}}">{{$favorite->book->title}}</a>
            </div>

            @endforeach
        </div>
    </div>
</div>

resources/views/livewire/genre-component.blade.php
<div>
    <x-slot name="header">
        <h2 class="text-2xl font-semibold leading-tight text-gray-800">
            @if($selectedGenre)
            {{$selectedGenre->name}}
            @else
                {{ __('Genre list (❛‿❛)') }}
            @endif
        </h2>
    </x-slot>
    <div class="p-5 mx-auto mt-10 bg-white rounded-lg shadow-lg max-w-7xl">
        @if ($selectedGenre)
            <div class="pt-5">
                @forelse ($selectedGenre->books as $book)
                    <div class="flex w-full">
                        <div class="flex w-full">
                            <div class="flex pr-1">
                                @if (!$book->user_favorite)
                                    <x-heroicon-o-bookmark wire:click="favoriteBook({{ $book->id }})" class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                                @else
                                    <x-heroicon-s-bookmark wire:click="favoriteBook({{ $book->id }})" class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                                @endif
                            </div>
                            <h2 class="text-lg">{{ $book->title }}</h2>
                            <div class="flex">
                                @if (!$book->user_like)
                                    <x-heroicon-o-thumb-up wire:click="likeBook({{ $book->id }})" class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                                @else
                                    <x-heroicon-s-thumb-up wire:click="likeBook({{ $book->id }})" class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                                @endif
                                <span class="mt-2 ml-2 text-xs text-pink-600">({{ $book->likes->count() }})</span>
                            </div>
                            <div class="flex">
                                @if (!$book->user_dislike)
                                    <x-heroicon-o-thumb-down wire:click="dislikeBook({{ $book->id }})" class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                                @else
                                    <x-heroicon-s-thumb-down wire:click="dislikeBook({{ $book->id }})" class="w-6 h-6 ml-5 text-pink-500 cursor-pointer" />
                                @endif
                                <span class="mt-2 ml-2 text-xs text-pink-600">({{ $book->dislikes->count() }})</span>
                            </div>
                        </div>
                    </div>
                    <div class="w-full px-12 pb-2">
                        by {{ $book->author }} <span class="text-xs">({{ $book->user->name }})</span>
                        <hr class="my-2">
                        <p>
                            {{ $book->short_description }}
                        </p>
                        <p class="py-2">
                            <a class="px-2 py-1 text-xs text-white bg-blue-700 rounded hover:bg-blue-500" target="_blank" class="hover:underline" href="{{ $book->link }}">Buy Online</a>
                        </p>
                    </div>
                    <div class="flex w-full px-12 pb-10 space-x-2">
                        @foreach ($book->genres as $genre)
                            <a href="{{ route('GENRE', ['genreId' => $genre->id]) }}" class="px-2 py-1 text-xs text-white bg-pink-600 rounded-lg hover:bg-pink-300 hover:text-pink-600">{{ $genre->name }}</a>
                        @endforeach
                    </div>
                @empty
                    {{ __('Es sind noch keine Bücher vorhanden.') }}
                @endforelse
                <div class="w-full mt-10">
                    <a href="{{ route('GENRE') }}" class="px-2 py-1 mt-5 text-pink-400 bg-pink-200 rounded hover:bg-pink-400 hover:text-white">Zurück</a>

                </div>
            </div>
        @else
            <div class="flex justify-between w-full py-4">
                <h1 class="text-2xl">All genres (•◡•) /</h1>
                <button class="px-2 py-1 text-pink-400 bg-pink-200 rounded hover:bg-pink-400 hover:text-white" wire:click="showCreateForm">Neuer Eintrag</button>
            </div>
            @if ($showCreate)
                <div class="w-full py-2">
                    <x-jet-label for="name" value="{{ __('Name') }}" />
                    <x-jet-input id="name" class="block w-full mt-1" type="text" name="name" wire:model="name" required />
                    <div class="flex justify-between w-full pt-5">
                        <button class="px-2 py-1 text-white bg-red-800 rounded hover:bg-red-400" wire:click="cancel">Abbrechen</button>
                        <button class="px-2 py-1 text-pink-400 bg-pink-200 rounded hover:bg-pink-400 hover:text-white" wire:click="save">Speichern</button>
                    </div>
                </div>
            @else
                <div class="flex flex-col w-full space-y-2">
                    @foreach ($genres as $genre)
                        <div class="flex space-x-2">
                            <x-heroicon-o-trash wire:click="deleteGenre({{ $genre->id }})" class="w-4 h-4 text-red-600 cursor-pointer">
                                </x-heroicon-o-pencil>
                                <x-heroicon-o-pencil wire:click="editGenre({{ $genre->id }})" class="w-4 h-4 text-pink-600 cursor-pointer"></x-heroicon-o-pencil>
                                <a class="hover:underline" href="{{ route('GENRE', ['genreId' => $genre->id]) }}">{{ $genre->name }}</a> ({{ $genre->books_count }})
                        </div>
                    @endforeach
                </div>

            @endif
        @endif
    </div>
</div>

resources/views/livewire/henni.blade.php
<div>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Henni Popo') }}
        </h2>
    </x-slot>
    <div class="mt-10 max-w-7xl mx-auto bg-white p-5 shadow-lg rounded-lg">
        Hallo Ich bins
    </div>
</div>

resources/views/livewire/user-component.blade.php
<div>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Users') }}
        </h2>
    </x-slot>
    <div class="p-5 mx-auto mt-10 bg-white rounded-lg shadow-lg max-w-7xl">
        <div class="flex flex-wrap">
            @foreach ($users as $user)
                <div class="flex flex-col py-2 mr-5">
                    <img src="{{ $user->profile_photo_url }}" alt="{{ $user->name }}" class="object-cover w-20 h-20 rounded-full">
                    <h1 class="text-lg">{{ $user->name }}</h1>
                    <span class="text-sm">Since: {{ $user->created_at->format('d.m.Y') }}</span>
                    <span class="text-sm">Books: {{ $user->books_count }}</span>
                </div>
            @endforeach
        </div>
    </div>
</div>